name:                potato-flow
version:             0.1.0.0
github:              "githubuser/potato-flow"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/potato-flow#readme>


ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
#- -Werror


default-extensions:
- ApplicativeDo
- BangPatterns
- DataKinds
- ConstraintKinds
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- NoImplicitPrelude


dependencies:
- base >= 4.7 && < 5
- relude
- reflex
- aeson
- containers
- bytestring
- ilist
- dependent-sum
- dependent-sum-template
- dependent-map
- ref-tf
- text

#- smash
- deepseq
- binary
- hashable

- these
- containers
- patch
- template-haskell
- reflex-dynamic-containers
- reflex-test-host
- reflex-potatoes
- extra
- linear
- MonadRandom
- random-shuffle
- constraints-extras


library:
  source-dirs: src
  exposed-modules:
    - Potato.Flow
    - Reflex.Data.Directory

executables:
  memorytests:
    main: newmemtest.hs
    source-dirs: benchmarks
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    dependencies:
    - potato-flow

tests:
  potato-flow-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - potato-flow
    - HUnit
    - hspec
    - hspec-contrib
    - pretty-simple
