name: Release

on: 
  push:
    tags:
    - 'v*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.2.5'
        cabal-version: '3.2'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies
    - name: Build
      run: cabal build all

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz"

    - name: Upload package candidate to hackage
      uses: haskell-actions/hackage-publish@v1
      with:
        hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
        packagesPath: ${{ runner.temp }}/packages
        docsPath: ${{ runner.temp }}/docs
        publish: false

